# This file is generated by rake. Do not edit.

module Clipr
  module Api
    module Struct
      # /************************************************************/
      # /* bitMapHashNode STRUCTURE:                                */
      # /************************************************************/
      # struct bitMapHashNode
      #   {
      #    struct bitMapHashNode *next;
      #    long count;
      #    int depth;
      #    unsigned int permanent : 1;
      #    unsigned int markedEphemeral : 1;
      #    unsigned int neededBitMap : 1;
      #    unsigned int bucket : 29;
      #    char *contents;
      #    unsigned short size;
      #   };
      #
      class BitMapHashNode < FFI::Struct
        layout :next, :pointer, 0,
               :count, :long, 4,
               :depth, :int, 8,
               :contents, :string, 16,
               :size, :ushort, 20










      end
    end
  end
end
