# This file is generated by rake. Do not edit.

module Clipr
  module Api
    module Struct
      # /************************************************************/
      # /* externalAddressHashNode STRUCTURE:                                */
      # /************************************************************/
      # struct externalAddressHashNode
      #   {
      #    struct externalAddressHashNode *next;
      #    long count;
      #    int depth;
      #    unsigned int permanent : 1;
      #    unsigned int markedEphemeral : 1;
      #    unsigned int neededPointer : 1;
      #    unsigned int bucket : 29;
      #    void *externalAddress;
      #    unsigned short type;
      #   };
      #
      class ExternalAddressHashNode < FFI::Struct
        layout :next, :pointer, 0,
               :count, :long, 4,
               :depth, :int, 8,
               :externalAddress, :pointer, 16,
               :type, :ushort, 20










      end
    end
  end
end
