# This file is generated by rake. Do not edit.

module Clipr
  module Api
    module Struct
      # /************************************************************/
      # /* floatHashNode STRUCTURE:                                  */
      # /************************************************************/
      # struct floatHashNode
      #   {
      #    struct floatHashNode *next;
      #    long count;
      #    int depth;
      #    unsigned int permanent : 1;
      #    unsigned int markedEphemeral : 1;
      #    unsigned int neededFloat : 1;
      #    unsigned int bucket : 29;
      #    double contents;
      #   };
      #
      class FloatHashNode < FFI::Struct
        layout :next, :pointer, 0,
               :count, :long, 4,
               :depth, :int, 8,
               :contents, :double, 16










      end
    end
  end
end
