# This file is generated by rake. Do not edit.

module Clipr
  module Api
    module Struct
      # /************************************************************/
      # /* integerHashNode STRUCTURE:                               */
      # /************************************************************/
      # struct integerHashNode
      #   {
      #    struct integerHashNode *next;
      #    long count;
      #    int depth;
      #    unsigned int permanent : 1;
      #    unsigned int markedEphemeral : 1;
      #    unsigned int neededInteger : 1;
      #    unsigned int bucket : 29;
      #    long long contents;
      #   };
      #
      class IntegerHashNode < FFI::Struct
        layout :next, :pointer, 0,
               :count, :long, 4,
               :depth, :int, 8,
               :contents, :long_long, 16










      end
    end
  end
end
